Vagrant.configure("2") do |config|

  # machine
  config.vm.define "nim-centos8" do |vm1|
    vm1.vm.box = "centos/8"
    vm1.vm.hostname = "nim-centos8"
    vm1.vm.network "private_network", ip: "192.168.55.98"
    vm1.vm.provision "file", source: "nginx-instance-manager-eval.lic", destination: "/tmp/nginx-instance-manager-eval.lic"
    vm1.vm.provision "file", source: "nginx-instance-manager-eval.cer", destination: "/tmp/nginx-instance-manager-eval.cer"
    vm1.vm.provision "file", source: "nginx-instance-manager-eval.key", destination: "/tmp/nginx-instance-manager-eval.key"
    vm1.disksize.size = '20GB'
    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "nim-centos8"
      vb.cpus = 1
      vb.memory = 2048
    end
  end
  
# machine
config.vm.define "nginx-oss-centos8" do |vm1|
  vm1.vm.box = "centos/8"
  vm1.vm.hostname = "nginx-oss-centos8"
  vm1.vm.network "private_network", ip: "192.168.55.99"
  vm1.disksize.size = '20GB'
  vm1.vm.provider "virtualbox" do |vb|
    vb.name = "nginx-oss-centos8"
    vb.cpus = 1
    vb.memory = 2048
  end
end

end
