Vagrant.configure("2") do |config|

  # machine
  config.vm.define "nginx-instance-manager" do |vm1|
    vm1.vm.box = "ubuntu/focal64"
    vm1.vm.hostname = "nginx-instance-manager"
    vm1.vm.network "private_network", ip: "192.168.55.103"
    vm1.vm.provision "file", source: "nginx-instance-manager-eval.lic", destination: "/tmp/nginx-instance-manager-eval.lic"
    vm1.vm.provision "file", source: "nginx-instance-manager-eval.cer", destination: "/tmp/nginx-instance-manager-eval.cer"
    vm1.vm.provision "file", source: "nginx-instance-manager-eval.key", destination: "/tmp/nginx-instance-manager-eval.key"
    vm1.disksize.size = '20GB'
    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "nginx-instance-manager"
      vb.cpus = 1
      vb.memory = 2048
    end
  end
  
# machine
config.vm.define "nginx-oss" do |vm1|
  vm1.vm.box = "centos/7"
  vm1.vm.hostname = "nginx-oss"
  vm1.vm.network "private_network", ip: "192.168.55.102"
  vm1.disksize.size = '20GB'
  vm1.vm.provider "virtualbox" do |vb|
    vb.name = "nginx-oss"
    vb.cpus = 1
    vb.memory = 2048
  end
end

# machine
config.vm.define "nginx-plus" do |vm1|
  vm1.vm.box = "ubuntu/focal64"
  vm1.vm.hostname = "nginx-plus"
  vm1.vm.network "private_network", ip: "192.168.55.101"
  vm1.disksize.size = '20GB'
  vm1.vm.provider "virtualbox" do |vb|
    vb.name = "nginx-plus"
    vb.cpus = 1
    vb.memory = 2048
  end
end

# machine
config.vm.define "apache" do |vm1|
  vm1.vm.box = "ubuntu/trusty32"
  vm1.vm.hostname = "apache"
  vm1.vm.network "private_network", ip: "192.168.55.94"
  vm1.disksize.size = '20GB'
  vm1.vm.provider "virtualbox" do |vb|
    vb.name = "apache"
    vb.cpus = 1
    vb.memory = 2048
  end
end

end
